version: "3.7"

services:
  laravel-app:
    container_name: laravel-app
    image: workshop/laravel:latest
    build:
      context: .
      dockerfile: infra/docker/app/Dockerfile
    tty: true
    volumes:
      - ./:/var/www/laravel
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
      LC_ALL: "ja_JP.UTF-8"

  laravel-db:
    container_name: laravel-db
    image: workshop/laravel-db:latest
    build:
      context: .
      dockerfile: infra/docker/db/Dockerfile
    volumes:
      - ./infra/docker/persistence/db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: laravel_root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
      LC_ALL: "ja_JP.UTF-8"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb-use-native-aio=0 --sql_mode="STRICT_TRANS_TABLES"

  laravel-db-manager:
    container_name: laravel-db-manager
    image: workshop/laravel-db-manager:latest
    build:
      context: .
      dockerfile: infra/docker/db-manager/Dockerfile
    depends_on:
      - laravel-db
    ports:
      - "8080:80"
    environment:
      PMA_HOSTS: laravel-db
      PMA_USER: laravel
      PMA_PASSWORD: laravel
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
      LC_ALL: "ja_JP.UTF-8"
